# Constants for Rella Analytics

BOULEVARD_CATEGORY_MAPPING = {
    # Injectables (Services)
    "Botox / Dysport": "Injectables",
    "Dermal Fillers": "Injectables",
    "Kybella": "Injectables",
    "Botox/Dysport Return Clients": "Injectables",
    "NEW PATIENT BOTOX/DYSPORT": "Injectables",
    "Botox & Filler": "Injectables",
    "Filler": "Injectables",
    "Sculptra": "Injectables",
    # Injectables (Products)
    "Botox": "Injectables",
    "Dysport": "Injectables",
    "Juvederm Ultra XC": "Injectables",
    "Juvederm Voluma XC": "Injectables",
    "Juvederm Vollure XC": "Injectables",
    "Restylane Contour": "Injectables",
    "Juvederm Ultra Plus 1ML": "Injectables",
    "Juvederm Ultra XC .55mL": "Injectables",
    "Juvederm Volbella XC": "Injectables",
    "Juvederm Volux XC": "Injectables",
    "Restylane Defyne": "Injectables",
    "Restylane Eyelight": "Injectables",
    "Restylane Kysse": "Injectables",
    "Restylane L": "Injectables",
    "Restylane Lyft": "Injectables",
    "Restylane Refyne": "Injectables",
    "PRP Injection": "Injectables",
    # Facials
    "Signature Hydrafacial": "Facials",
    "Platinum Hydrafacial": "Facials",
    "Deluxe Hydrafacial": "Facials",
    "Microdermabrasion Basic Facial": "Facials",
    "Acne Facial": "Facials",
    "Anti Aging Facial": "Facials",
    "C02 Mask": "Facials",
    "Dermaplaning Add On": "Facials",
    "Express Facial": "Facials",
    "Hands Hydrafacial": "Facials",
    "Hydrafacial Special": "Facials",
    "MicroPeel Sensitive": "Facials",
    "Microdermabrasion Deluxe Facial": "Facials",
    "Perk Eye Add-On (HydraFacial)": "Facials",
    "Perk Lip Add-On (HydraFacial)": "Facials",
    "Universal Peel": "Facials",
    "Jelly mask": "Facials",
    "TCA Peel": "Facials",
    "MicroPeel Plus 20": "Facials",
    "Hydrfacial Lip Perk": "Facials",
    "Hydrafacial Perk Eye": "Facials",
    # Laser
    "Laser Hair Removal - Medium Area": "Laser",
    "Laser Hair Removal - Upper/ Lower Face Area Package": "Laser",
    "Laser Hair Removal Large Area - a la carte": "Laser",
    "Erbium Hands Add-On": "Laser",
    "Spider Vein Removal": "Laser",
    "CO2 Skin Resurfacing": "Laser",
    "C02 Skin Resurfacing Special $750": "Laser",
    "C02 Skin Resurfacing Special $997": "Laser",
    "IPL Full Face - Package (3 Treatments)": "Laser",
    "Tattoo Removal": "Laser",
    "Erbium Special": "Laser",
    "Initial Laser Consult": "Laser",
    "C02 Décolleté Add On": "Laser",
    "C02 For You Bundle": "Laser",
    "C02 Neck Add On": "Laser",
    "C02 Skin Resurfacing": "Laser",
    "C02 Special": "Laser",
    "IPL - Full Face": "Laser",
    "IPL Neck Add-On": "Laser",
    "IPL special": "Laser",
    "Laser Hair Removal - Brazilian Area Package": "Laser",
    "Laser Hair Removal - Large Area Package": "Laser",
    "Laser Hair Removal - Medium Area Package": "Laser",
    "Laser Hair Removal - Small Area Package": "Laser",
    "Laser Hair Removal Medium Area - a la carte": "Laser",
    "Laser Hair Removal Small Area - a la carte": "Laser",
    "Skin Resurfacing Full Face - Erbium": "Laser",
    # Skincare/Retail Products
    "Powder Defense": "Retail/Skincare",
    "Tox Membership": "Retail/Membership",
    "Filler 12x Month Membership": "Retail/Membership",
    "Brightening Even Skin Tone Pads": "Retail/Skincare",
    "Hydroquinone Powder": "Retail/Skincare",
    "AHA / BHA Exfoliating Polish": "Retail/Skincare",
    "Aquaglow Hyaluronic Acid": "Retail/Skincare",
    "Blemish + Age Defense": "Retail/Skincare",
    "Bloom Membership": "Retail/Membership",
    "C E Ferulic": "Retail/Skincare",
    "Complexion Gly-Sal Pads": "Retail/Skincare",
    "Discoloration Defense": "Retail/Skincare",
    "Dual Active Phyto GF": "Retail/Skincare",
    "Glycolic 10 Renew Overnight": "Retail/Skincare",
    "Hydrate Membership": "Retail/Membership",
    "Hydrating B5 Gel": "Retail/Skincare",
    "Lipid Cloud": "Retail/Skincare",
    "P-TIOX": "Retail/Skincare",
    "Peptide Neck Cream": "Retail/Skincare",
    "Phyto Balance": "Retail/Skincare",
    "Plump It! SPF 30": "Retail/Skincare",
    "Radiant Glow Lactic Acid": "Retail/Skincare",
    "Sheer Defense": "Retail/Skincare",
    "Silymarin CF": "Retail/Skincare",
    "Simply Clean": "Retail/Skincare",
    "Skincare Kit": "Retail/Skincare",
    "Tinted Defense": "Retail/Skincare",
    "Blemish Corrective Treatment Serum": "Retail/Skincare",
    "Tox and Filler Membership": "Retail/Membership",
    # Wellness/Weight Loss
    "Semaglutide - weekly injection": "Wellness/Weight Loss",
    "Semaglutide - monthly pickup/weigh in": "Wellness/Weight Loss",
    "Tirzepatide - weekly injection": "Wellness/Weight Loss",
    "1st Weight Loss Appt (AFTER CONSULT)": "Wellness/Weight Loss",
    "Semaglutide x1 Month Supply": "Wellness/Weight Loss",
    "Semaglutide x3 Month Supply": "Wellness/Weight Loss",
    "Lipo-C / MIC": "Wellness/Weight Loss",
    "Vitamin D": "Wellness/Weight Loss",
    "B-12 Injection": "Wellness/Weight Loss",
    "Semaglutide/Tirzepatide Phone Consultation": "Wellness/Weight Loss",
    "Semaglutide x6 month Supply": "Wellness/Weight Loss",
    "semaglutide single injection": "Wellness/Weight Loss",
    "Tirzepatide 1x Month": "Wellness/Weight Loss",
    "Tirzepatide 3X Months Supply": "Wellness/Weight Loss",
    "Tirzepatide - monthly pickup": "Wellness/Weight Loss",
    "Tirzepatide 1x Single Dose": "Wellness/Weight Loss",
    # Wellness/IV Therapy (NEW CATEGORY)
    "B-Complex": "IV Therapy",
    "Beauty/Glow Blend": "IV Therapy",
    "Glutathione": "IV Therapy",
    "Hangover Cure": "IV Therapy",
    "Immunity Blend": "IV Therapy",
    "Myers' Cocktail": "IV Therapy",
    "NAD + Therapy": "IV Therapy",
    "IV Special": "IV Therapy",
    "Migraine/Pain Relief": "IV Therapy",
    # Other Services
    "PRP Add-On": "Other Services",
    "RF Microneedling": "Other Services",
    "Hylenex": "Other Services",
    "PRP Hair Restoration": "Other Services",
    "Additional Syringe": "Other Services",
    "Body Tone- Muscle Toning 1x treatment": "Other Services",
    "BodySculpt' Contouring1x treatment": "Other Services",
    "BodyTone Special": "Other Services",
    "Pronox": "Other Services",
    "RF Microneedling Face + Neck Package (3 Treatments)": "Other Services",
    "RF Microneedling Face Package (3 Treatments)": "Other Services",
    "RF Microneedling Full Face Package (3)": "Other Services",
    "Shaving Fee": "Other Services",
    "Skin Stylus Microneedling Package (3 Treatments)": "Other Services",
    "Skin Stylus Neck Add on": "Other Services",
    "Vaginal Rejuvenation": "Other Services",
    # Consults/Followups (Often $0, maybe categorize differently?)
    "Initial Microneedling Consult": "Consultation/Followup",
    "C02- Follow up": "Consultation/Followup",
    "Neurotoxins (Botox/Dysport) /Filler/PRP/Sculptra Follow Up": "Consultation/Followup",
    "Initial Skin Health Consult": "Consultation/Followup",
    "New Patient Consult": "Consultation/Followup",
    # Membership/Account Adjustments (NEW CATEGORY)
    "Membership fee corrections": "Membership/Account Adjustment",
    "Account Credit Adjustment": "Membership/Account Adjustment",
    # Default/Uncategorized
    "DEFAULT_CATEGORY": "Uncategorized" # A default for items not in the map
} 