import React, { useState } from 'react';
import { useOutletContext } from 'react-router-dom';
import {
  Box,
  Paper,
  Typography,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  IconButton,
  Alert,
  AlertTitle,
  CircularProgress,
  Tooltip,
  Modal,
  Button,
  Card,
  CardContent
} from '@mui/material';
import { Info as InfoIcon, Warning as WarningIcon, OpenInFull as OpenInFullIcon, Close as CloseIcon } from '@mui/icons-material';
import { formatCurrency, formatPercentage } from './common/ProfitCard';
import { BarChart, Bar, XAxis, YAxis, Tooltip as RechartsTooltip, ResponsiveContainer, Cell } from 'recharts';
import { saveAs } from 'file-saver';

function arrayToCSV(data) {
  if (!data.length) return '';
  const headers = Object.keys(data[0]);
  const csvRows = [headers.join(',')];
  for (const row of data) {
    csvRows.push(headers.map(h => JSON.stringify(row[h] ?? '')).join(','));
  }
  return csvRows.join('\n');
}

function downloadCSV(data, filename = 'products.csv') {
  const csv = arrayToCSV(data);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, filename);
}

function ProductProfitability(props) {
  console.log("ProductProfitability mounted");
  const { loading, error, kpiData } = useOutletContext();
  console.log("kpiData", kpiData);
  const [expanded, setExpanded] = useState(false);

  // Transform the array into a format suitable for table rendering
  const itemsArray = (kpiData && kpiData.items)
    ? kpiData.items
        .filter(item => item.type === 'product')
        .map((item, index) => ({
          id: index.toString(),
          name: item.name,
          type: item.type,
          quantity: item.quantity,
          sales: item.total_sales,
          cost: item.total_cost,
          profit: item.total_profit,
          profit_margin_percentage: item.profit_margin,
          isAdjusted: false,
          isCostEstimated: false
        }))
    : [];
  console.log("Number of products in kpiData.items:", itemsArray.length);

  // Sort by profit descending
  const sortedItems = [...itemsArray].sort((a, b) => b.profit - a.profit);
  const top5 = sortedItems.slice(0, 5);

  // Chart data
  const chartData = top5.map(item => ({ name: item.name, profit: item.profit }));
  const barColors = ['#d1365f', '#f44336', '#ef5350', '#e57373', '#ff8a80'];

  // Tooltip texts for headers
  const tooltips = {
    name: "The name of the product or service as returned by the Boulevard API.",
    type: "Indicates whether the item is a 'product' or a 'service'.",
    qty: "Total quantity of this item sold across all orders in the selected period.",
    sales: "Total sales revenue generated by this item (sum of line item currentSubtotal from Boulevard API). May include adjustments from backend heuristics (*).",
    cost: "Total cost for this item (Quantity Sold * Unit Cost). Product costs come from inventory data or fallback to 40% for products not in inventory. Service costs are only shown when available, otherwise zero.",
    profit: "Calculated as Total Sales - Total Cost for this item.",
    margin: "Calculated as (Total Profit / Total Sales) * 100 for this item."
  };

  if (error) {
    return (
      <Paper sx={{ p: 3 }}>
        <Alert 
          severity="error"
          icon={<WarningIcon />}
          sx={{ mb: 2 }}
        >
          <AlertTitle>API Error</AlertTitle>
          Unable to load profitability data from the API.
          <Box component="pre" sx={{ mt: 1, p: 1, bgcolor: 'error.light', borderRadius: 1, fontSize: '0.875rem' }}>
            {typeof error === 'string' ? error : error?.message || 'An unknown error occurred.'}
          </Box>
          <Typography variant="body2" sx={{ mt: 2 }}>
            Please try again later or contact support if the issue persists.
          </Typography>
        </Alert>
      </Paper>
    );
  }

  if (loading) {
    return (
      <Paper sx={{ p: 3, display: 'flex', flexDirection: 'column', alignItems: 'center', minHeight: 400, justifyContent: 'center' }}>
        <CircularProgress sx={{ mb: 2 }} />
        <Typography>Loading profitability data...</Typography>
      </Paper>
    );
  }

  if (!kpiData || !kpiData.items || kpiData.items.length === 0) {
    return (
      <Paper sx={{ p: 3, display: 'flex', flexDirection: 'column', alignItems: 'center', minHeight: 400, justifyContent: 'center' }}>
        <WarningIcon sx={{ fontSize: 48, color: 'warning.main', mb: 2 }} />
        <Typography variant="h6" gutterBottom>No Data Available</Typography>
        <Typography color="text.secondary">
          No profitability data was returned by the API for the selected period.
        </Typography>
      </Paper>
    );
  }

  // Table rendering function
  const renderTable = (data, maxHeight = 400) => (
    <TableContainer sx={{ maxHeight, overflowY: 'auto' }}>
      <Table stickyHeader>
        <TableHead>
          <TableRow>
            <TableCell>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                Name
                <Tooltip title={tooltips.name}>
                  <IconButton size="small">
                    <InfoIcon fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Box>
            </TableCell>
            <TableCell>
              <Box sx={{ display: 'flex', alignItems: 'center' }}>
                Type
                <Tooltip title={tooltips.type}>
                  <IconButton size="small">
                    <InfoIcon fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Box>
            </TableCell>
            <TableCell align="right">
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
                Qty Sold
                <Tooltip title={tooltips.qty}>
                  <IconButton size="small">
                    <InfoIcon fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Box>
            </TableCell>
            <TableCell align="right">
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
                Total Sales
                <Tooltip title={tooltips.sales}>
                  <IconButton size="small">
                    <InfoIcon fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Box>
            </TableCell>
            <TableCell align="right">
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
                Total Cost
                <Tooltip title={tooltips.cost}>
                  <IconButton size="small">
                    <InfoIcon fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Box>
            </TableCell>
            <TableCell align="right">
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
                Total Profit
                <Tooltip title={tooltips.profit}>
                  <IconButton size="small">
                    <InfoIcon fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Box>
            </TableCell>
            <TableCell align="right">
              <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end' }}>
                Profit Margin
                <Tooltip title={tooltips.margin}>
                  <IconButton size="small">
                    <InfoIcon fontSize="small" />
                  </IconButton>
                </Tooltip>
              </Box>
            </TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          {data.filter(item => item && item.id != null).map((item) => (
            <TableRow key={item.id} hover>
              <TableCell>{item.name}</TableCell>
              <TableCell sx={{ textTransform: 'capitalize' }}>{item.type}</TableCell>
              <TableCell align="right">{item.quantity}</TableCell>
              <TableCell align="right">{formatCurrency(item.sales)}</TableCell>
              <TableCell align="right">{formatCurrency(item.cost)}</TableCell>
              <TableCell align="right">{formatCurrency(item.profit)}</TableCell>
              <TableCell align="right">{formatPercentage(item.profit_margin_percentage)}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );

  // Before rendering the modal table, log the number of products
  if (expanded) {
    console.log("Modal: Number of products shown:", sortedItems.length);
  }

  return (
    <Card sx={{ p: 3, position: 'relative' }}>
      <CardContent>
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
          <Typography variant="h5">Product Profitability</Typography>
          <Box>
            <Button
              variant="outlined"
              size="small"
              startIcon={<OpenInFullIcon />}
              onClick={() => setExpanded(true)}
              sx={{ mr: 1 }}
            >
              Expand
            </Button>
            <Button
              variant="contained"
              size="small"
              onClick={() => downloadCSV(sortedItems)}
            >
              Download CSV
            </Button>
          </Box>
        </Box>
        {/* Bar Chart */}
        <Box sx={{ width: '100%', height: 250, mb: 2 }}>
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={chartData} layout="vertical" margin={{ left: 40, right: 20 }}>
              <XAxis type="number" tickFormatter={formatCurrency} />
              <YAxis dataKey="name" type="category" width={120} />
              <RechartsTooltip formatter={formatCurrency} />
              <Bar dataKey="profit" fill="#d1365f">
                {chartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={barColors[index % barColors.length]} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </Box>
        {/* Top 5 Table */}
        {renderTable(top5, 300)}
      </CardContent>
      {/* Expanded Modal */}
      <Modal open={expanded} onClose={() => setExpanded(false)}>
        <Box sx={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: '90vw', maxWidth: 900, bgcolor: 'background.paper', boxShadow: 24, borderRadius: 2, p: 3 }}>
          <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 2 }}>
            <Typography variant="h5">All Products</Typography>
            <Box>
              <Button
                variant="contained"
                size="small"
                onClick={() => downloadCSV(sortedItems, 'products.csv')}
                sx={{ mr: 1 }}
              >
                Download CSV
              </Button>
              <IconButton onClick={() => setExpanded(false)}><CloseIcon /></IconButton>
            </Box>
          </Box>
          {/* Bar Chart in Modal */}
          <Box sx={{ width: '100%', height: 250, mb: 2 }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={sortedItems} layout="vertical" margin={{ left: 40, right: 20 }}>
                <XAxis type="number" tickFormatter={formatCurrency} />
                <YAxis dataKey="name" type="category" width={120} />
                <RechartsTooltip formatter={formatCurrency} />
                <Bar dataKey="profit" fill="#d1365f">
                  {sortedItems.map((entry, index) => (
                    <Cell key={`cell-modal-${index}`} fill={barColors[index % barColors.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </Box>
          {/* Full Table with Scroll */}
          {renderTable(sortedItems, 400)}
        </Box>
      </Modal>
    </Card>
  );
}

export default ProductProfitability; 